package backup

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/trongdev/macos-backup/internal/config"
	"github.com/trongdev/macos-backup/internal/crypto"
)

func init() {
	Register(&MASHandler{})
}

// MASHandler exports Mac App Store app lists via the `mas` CLI.
type MASHandler struct{}

func (h *MASHandler) Name() string { return "mas" }

func (h *MASHandler) Discover(cfg *config.CategoryConfig) ([]FileEntry, error) {
	if _, err := exec.LookPath("mas"); err != nil {
		return nil, fmt.Errorf("mas CLI is not installed (install with: brew install mas)")
	}
	return []FileEntry{{Category: "mas", RelPath: "mas-list.txt"}}, nil
}

func (h *MASHandler) Backup(ctx context.Context, entries []FileEntry, dest string, enc crypto.Encryptor) (*CategoryResult, error) {
	result := &CategoryResult{
		CategoryName: "mas",
	}

	if err := os.MkdirAll(dest, 0755); err != nil {
		return nil, fmt.Errorf("creating mas backup dir: %w", err)
	}

	// Run `mas list` to get installed App Store apps
	output, err := exec.CommandContext(ctx, "mas", "list").Output()
	if err != nil {
		result.Warnings = append(result.Warnings, fmt.Sprintf("mas list failed: %v", err))
		return result, nil
	}

	// Write raw list
	listPath := filepath.Join(dest, "mas-list.txt")
	if err := os.WriteFile(listPath, output, 0644); err != nil {
		return nil, fmt.Errorf("writing mas list: %w", err)
	}

	result.Entries = append(result.Entries, ManifestEntry{
		Path:     "mas/mas-list.txt",
		Original: "mas-list.txt",
		Size:     int64(len(output)),
	})
	result.FileCount++

	// Generate install script for easy restore
	script := generateMASInstallScript(string(output))
	scriptPath := filepath.Join(dest, "mas-install.sh")
	if err := os.WriteFile(scriptPath, []byte(script), 0755); err != nil {
		result.Warnings = append(result.Warnings, fmt.Sprintf("writing install script: %v", err))
	} else {
		result.Entries = append(result.Entries, ManifestEntry{
			Path:     "mas/mas-install.sh",
			Original: "mas-install.sh",
			Size:     int64(len(script)),
		})
		result.FileCount++
	}

	return result, nil
}

// generateMASInstallScript creates a shell script from `mas list` output.
// Each line of `mas list` looks like: "497799835  Xcode (15.0)"
func generateMASInstallScript(masList string) string {
	var sb strings.Builder
	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("# Mac App Store apps - install script\n")
	sb.WriteString("# Generated by macback\n")
	sb.WriteString("# Run: bash mas-install.sh\n\n")
	sb.WriteString("if ! command -v mas &>/dev/null; then\n")
	sb.WriteString("  echo \"Error: mas CLI not found. Install with: brew install mas\"\n")
	sb.WriteString("  exit 1\n")
	sb.WriteString("fi\n\n")

	scanner := bufio.NewScanner(strings.NewReader(masList))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		// Extract app ID (first field)
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		appID := fields[0]
		// Rest is the app name
		appName := strings.Join(fields[1:], " ")
		sb.WriteString(fmt.Sprintf("echo \"Installing %s...\"\n", appName))
		sb.WriteString(fmt.Sprintf("mas install %s\n\n", appID))
	}

	return sb.String()
}
