package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// DefaultConfig returns the default configuration with all categories.
func DefaultConfig() *Config {
	return &Config{
		BackupDest: "~/macback-backups",
		Categories: map[string]*CategoryConfig{
			"ssh": {
				Enabled: true,
				Paths: []string{
					"~/.ssh/config",
					"~/.ssh/known_hosts",
					"~/.ssh/id_*",
					"~/.ssh/*.pub",
				},
				SecretPatterns: []string{"id_*", "!*.pub"},
				Exclude:        []string{"*.sock", "agent.*"},
			},
			"shell": {
				Enabled: true,
				Paths: []string{
					"~/.zshrc",
					"~/.zprofile",
					"~/.zshenv",
					"~/.bashrc",
					"~/.bash_profile",
					"~/.profile",
					"~/.aliases",
					"~/.functions",
				},
			},
			"git": {
				Enabled: true,
				Paths: []string{
					"~/.gitconfig",
					"~/.gitignore_global",
					"~/.git-credentials",
				},
				SecretPatterns: []string{".git-credentials"},
			},
			"dotfiles": {
				Enabled: true,
				Paths: []string{
					"~/.config/",
					"~/bin/",
					"~/scripts/",
					"~/.vimrc",
					"~/.tmux.conf",
				},
				Exclude: []string{
					"*.log",
					"Cache/",
					"CachedData/",
					"GPUCache/",
					"node_modules/",
				},
				SecretPatterns: []string{".env", ".env.*", "*secret*", "*credential*"},
			},
			"homebrew": {
				Enabled:      true,
				IncludeCasks: true,
				IncludeTaps:  true,
				IncludeMas:   false,
			},
			"pathbin": {
				Enabled: true,
				ScanDirs: []string{
					"/usr/local/bin",
					"~/bin",
					"~/go/bin",
					"~/.local/bin",
				},
				CatalogOnly: true,
				ExcludePrefixes: []string{
					"/usr/bin",
					"/bin",
					"/sbin",
				},
			},
			"mas": {
				Enabled: false, // requires `mas` CLI installed
			},
			"appsettings": {
				Enabled: true,
				Paths:   []string{"~/Library/Preferences/"},
				Exclude: []string{"com.apple.*", "*.lockfile"},
			},
			"apps": {
				Enabled: true,
				ScanDirs: []string{
					"/Applications",
					"~/Applications",
				},
				CatalogOnly: true,
			},
		},
		Encryption: EncryptionConfig{
			Enabled: true,
			GlobalSecretPatterns: []string{
				"*.pem",
				"*.key",
				"*.p12",
				"*.pfx",
				".env",
				".env.*",
			},
			Extension: ".age",
		},
	}
}

// WriteDefault writes the default config to the specified path.
func WriteDefault(path string) error {
	expandedPath, err := ExpandPath(path)
	if err != nil {
		return fmt.Errorf("expanding path: %w", err)
	}

	dir := filepath.Dir(expandedPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating config directory: %w", err)
	}

	cfg := DefaultConfig()
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	header := []byte("# macback configuration file\n# Generated by: macback init\n# Edit this file to customize what gets backed up.\n\n")
	content := append(header, data...)

	if err := os.WriteFile(expandedPath, content, 0644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	return nil
}
